### ISSUE TITLE
Task: Component Diagrams

### ISSUE THREAD

**Issue by zainu99** [OmerKSonmez/ISP-Project#15]
Component Diagrams are used in modeling the physical aspects of object oriented things (like video games) systems that are used for visualizing, specifying, and documenting. They focus on the physical implementation of various items.

**Comment by jasonisaperson** [comment]
![Image](https://github.com/OmerKSonmez/ISP-Project/assets/111066552/4e6c6d84-3b22-46b6-8acd-8aaa0cdfd0cf)
