### ISSUE TITLE
Task: Game Rules

### ISSUE THREAD

**Issue by OmerKSonmez** [OmerKSonmez/ISP-Project#17]
- Purpose of the game is to use the paddle to hit the ball and bounce it around the screen order to break all the bricks.
- Each color brick awards the player with a different amount of points
-  Player starts the game with 3 lives.
- A life is removed every time the player misses the ball
- The player loses a game if his live total decreases to 0
- The player wins the game if he breaks all the bricks successfully without losing all three lives
- #19

**Comment by OmerKSonmez** [comment]
Not yet fully completed as of 1/12/2024. Will be continuously worked on until development process is complete.

**Comment by zainu99** [comment]
goo goo gaa gaa

**Comment by zainu99** [comment]
There are five key elements in great games.

Game Characters.
**YOU**

Goals.
**POINTS**

Decisions.
**HIT BALL**

Rewards.
**HIGH SCORE**

Immersion and Presence
**QUICK REACTIONS**


-`https://www.getmecoding.com/design-a-great-video-game/`
