### ISSUE TITLE
Task: Random Brick Generation

### ISSUE THREAD

**Issue by OmerKSonmez** [OmerKSonmez/ISP-Project#32]
Each new game attempt spawns in different, randomly generated, set of bricks with different colors.

**Comment by OmerKSonmez** [comment]
#21

**Comment by maxwellwys** [comment]
# Create bricks with equally distributed colors
colors = [RED, BLUE, WHITE]
bricks = []
for row in range(5):
    for col in range(WIDTH // BRICK_WIDTH):
        brick_color = random.choice(colors)
        brick = pygame.Rect(col * BRICK_WIDTH, row * BRICK_HEIGHT, BRICK_WIDTH, BRICK_HEIGHT)
        bricks.append((brick, brick_color))

See brickBreakerGame.py main branch
