### ISSUE TITLE
Task: No more lives

### ISSUE THREAD

**Issue by OmerKSonmez** [OmerKSonmez/ISP-Project#35]
In our game, when you lose all of your lives, there will be a black screen with red words "You lost". Then the game ends. You have to restart your progress when you load up a new game.

**Comment by maxwellwys** [comment]
# Check if the ball reaches the bottom
        if ball.top > HEIGHT:
            lives -= 1
            if lives == 0:
                game_over = True  # Player loses
                print("Game Over! You ran out of lives.")
See brickBreakerGame.py main branch

**Comment by jasonisaperson** [comment]
#23
