### ISSUE TITLE
Task: Better Graphics and Visual Effects of Background

### ISSUE THREAD

**Issue by OmerKSonmez** [OmerKSonmez/ISP-Project#36]

**Comment by OmerKSonmez** [comment]
#24

**Comment by zainu99** [comment]
https://giphy.com/clips/buzzfeed-black-history-kids-reenact-leaders-fHBtsxI2CZgq2ZzwFm

**Comment by zainu99** [comment]
We added a pixal anime like backgorund and for visual effects we did physics on the ball bouncing along the paddle.
