### ISSUE TITLE
Task: Design Patterns

### ISSUE THREAD

**Issue by maxwellwys** [OmerKSonmez/ISP-Project#8]
- Design Patterns in code are the formalized and independent strategies for solving a common problem.
- Design Patterns in the actual program are the different patterns of colors, shapes or attributes in order to create one unique design.
- For our program, we plan to use many functions in order to not have many lines of code and make our project more overall more organized.
- When it comes to the actual design pattern of our project, we plan to have many different colors (whether they are neon or base) and shapes (rectangles and circles), which are present in all modern brick breaker games.
- We also plan on adding a nice background as well in order to make the game an overall more immersive experience.

**Comment by zainu99** [comment]
![Image](https://github.com/OmerKSonmez/ISP-Project/assets/111151359/be513e97-a464-4982-a422-9c4ef6b265e4)

**Comment by OmerKSonmez** [comment]
#20
